import { existsSync } from "node:fs";
import { join } from "node:path";
import { getAssetPath } from "./withBase";

/**
 * Convention: a post's hero illustration lives at
 * `public/images/posts/<post-id>/hero.svg` (generated by
 * `bun scripts/generate-post-images.ts`).
 *
 * Returns the base-prefixed URL when the file exists, otherwise undefined so
 * templates can skip the hero block. The existsSync call runs at build time
 * only (Astro frontmatter), never in the browser.
 */
export function getPostHeroImage(id: string): string | undefined {
  const slug = id.split("/").pop() ?? id;
  const file = join(process.cwd(), "public/images/posts", slug, "hero.svg");
  return existsSync(file)
    ? getAssetPath(`images/posts/${slug}/hero.svg`)
    : undefined;
}
